default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("DB_HOST") { "mysql" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root
  # password:

development:
  <<: *default
  database: rails7_on_docker_development

test:
  <<: *default
  database: rails7_on_docker_test

# production:
#   <<: *default
#   database: app_production
#   username: app
#   password: <%= ENV["APP_DATABASE_PASSWORD"] %>
